### ISSUE TITLE
error with cycle in symmetry module

### ISSUE THREAD

**Issue by juditzador** [zadorlab/KinBot#18]
```
Traceback (most recent call last):
  File "/home/jzador/.local/bin/kinbot", line 11, in <module>
    load_entry_point('KinBot', 'console_scripts', 'kinbot')()
  File "/home/jzador/KinBot/kinbot/kb.py", line 173, in main
    rg.generate()
  File "/home/jzador/KinBot/kinbot/reaction_generator.py", line 316, in generate
    prod_opt.do_optimization()
  File "/home/jzador/KinBot/kinbot/optimize.py", line 253, in do_optimization
    symmetry.calculate_symmetry(self.species)
  File "/home/jzador/KinBot/kinbot/symmetry.py", line 164, in calculate_symmetry
    if species.atomid[cyc_nei[0]] == species.atomid[cyc_nei[1]]:
IndexError: list index out of range
```

**Comment by adewyer** [comment]
Was this also addressed in the changes you made over the weekend?

**Comment by adewyer** [comment]
According to pull request this issue is closed
