### ISSUE TITLE
Having trouble using pesviewer?

### ISSUE THREAD

**Issue by liqiang4567** [zadorlab/KinBot#72]
When I use the command pesviewer pesviewer.inp to visualize the results, I get the following error. But the result is still normal output.

Traceback (most recent call last):
  File "/home/xxx/software/anaconda3/envs/kinbot/bin/pesviewer", line 10, in <module>
    sys.exit(main())
  File "/home/xxx/software/anaconda3/envs/kinbot/lib/python3.8/site-packages/pesviewer/pesviewer.py", line 1602, in main
    create_interactive_graph(meps)
  File "/home/xxx/software/anaconda3/envs/kinbot/lib/python3.8/site-packages/pesviewer/pesviewer.py", line 1411, in create_interactive_graph
    norm_energy = (ts.energy - min_ts_energy) / ts_energy_range
ZeroDivisionError: float division by zero

**Comment by juditzador** [comment]
Can you please post the questions related to the PESViewer into our PESViewer repo? Also, please post your input, it is hard to debug a problem like this.

**Comment by liqiang4567** [comment]
Hello, input is provided in the attachment
[pesviewer.txt](https://github.com/zadorlab/KinBot/files/14367721/pesviewer.txt)

**Comment by juditzador** [comment]
Yes, the reason is that you only have one transition state. This is an edge case, we can solve it, but it sounds like the code is still working. Again, please post pesviewer related questions into the pesviewer repo to keep things straight. Thank you.
