### ISSUE TITLE
 invalid syntax   match atom_pattern:

### ISSUE THREAD

**Issue by liqiang4567** [zadorlab/KinBot#73]
Hello, I installed the latest kinbot version, the following error appears, how to solve? Thank you!

Traceback (most recent call last):
  File "/home/XXX/software/anaconda3/envs/kinbot_code/bin/kinbot", line 5, in <module>
    from kinbot.kb import main
  File "/home/XXX/Kinbot/kinbot_code/Kinbot_code/Kinbot/kinbot/kb.py", line 10, in <module>
    from kinbot.reaction_finder import ReactionFinder
  File "/home/XXX/Kinbot/kinbot_code/Kinbot_code/Kinbot/kinbot/reaction_finder.py", line 29, in <module>
    from kinbot.reactions.reac_R_Addition_MultipleBond import RAdditionMultipleBond
  File "/home/XXX/Kinbot/kinbot_code/Kinbot_code/Kinbot/kinbot/reactions/reac_R_Addition_MultipleBond.py", line 44
    match atom_pattern:
          ^
SyntaxError: invalid syntax

**Comment by juditzador** [comment]
It is not a syntax error, this is a structure introduced in python 3.10 (match/case). I can revert this back to python 3.8 compatible code, I'll do it and let you know.

**Comment by liqiang4567** [comment]
Thanks, can I upgrade python=3.10 to solve the problem?

**Comment by juditzador** [comment]
Yes, that's another solution. Let me know if that works.

**Comment by liqiang4567** [comment]
Update to python=3.10 and the program can run normally
